import { ref } from 'vue';

const languages = {
  //English
  en: {
    title: 'Chipsytok',
    login: 'Log in',
    signup: 'Sign up',
    firstName: 'First Name',
    lastName: 'Last Name',
    username: 'Username',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    email: 'Email',
    phoneNumber: 'Phone Number',
    forgotPassword: 'Forgot password?',
    noAccount: "Don't have an account?",
    haveAccount: 'Already have an account?',
    chooseLanguage: 'Choose your language',
    sendResetLink: 'Send Reset Link',
    cancel: 'Cancel',
    resetPassword: 'Reset your password',
    viaEmail: 'Via Email',
    viaUsername: 'Via Username',
    verificationTitle: 'Enter 5-digit verification code',
    verify: 'Verify',
    verificationFailed: 'Verification failed',
    placeholderPhone: 'Phone number, username, or email',
    errors: {
      usernameRequired: 'Username is required',
      passwordRequired: 'Password is required',
      emailRequired: 'Email is required',
      passwordsMismatch: 'Passwords do not match',
      generalError: 'An error occurred. Please try again.',
    },
    countries: {
      '+1': 'United States/Canada',
      '+7': 'Russia/Kazakhstan',
      '+20': 'Egypt',
      '+27': 'South Africa',
      '+30': 'Greece',
      '+31': 'Netherlands',
      '+32': 'Belgium',
      '+33': 'France',
      '+34': 'Spain',
      '+36': 'Hungary',
      '+39': 'Italy',
      '+40': 'Romania',
      '+41': 'Switzerland',
      '+43': 'Austria',
      '+44': 'United Kingdom',
      '+45': 'Denmark',
      '+46': 'Sweden',
      '+47': 'Norway',
      '+48': 'Poland',
      '+49': 'Germany',
      '+51': 'Peru',
      '+52': 'Mexico',
      '+53': 'Cuba',
      '+54': 'Argentina',
      '+55': 'Brazil',
      '+56': 'Chile',
      '+57': 'Colombia',
      '+58': 'Venezuela',
      '+60': 'Malaysia',
      '+61': 'Australia',
      '+62': 'Indonesia',
      '+63': 'Philippines',
      '+64': 'New Zealand',
      '+65': 'Singapore',
      '+66': 'Thailand',
      '+81': 'Japan',
      '+82': 'South Korea',
      '+84': 'Vietnam',
      '+86': 'China',
      '+90': 'Turkey',
      '+91': 'India',
      '+92': 'Pakistan',
      '+93': 'Afghanistan',
      '+94': 'Sri Lanka',
      '+95': 'Myanmar',
      '+98': 'Iran',
      '+211': 'South Sudan',
      '+212': 'Morocco',
      '+213': 'Algeria',
      '+216': 'Tunisia',
      '+218': 'Libya',
      '+220': 'Gambia',
      '+221': 'Senegal',
      '+222': 'Mauritania',
      '+223': 'Mali',
      '+224': 'Guinea',
      '+225': 'Ivory Coast',
      '+226': 'Burkina Faso',
      '+227': 'Niger',
      '+228': 'Togo',
      '+229': 'Benin',
      '+230': 'Mauritius',
      '+231': 'Liberia',
      '+232': 'Sierra Leone',
      '+233': 'Ghana',
      '+234': 'Nigeria',
      '+235': 'Chad',
      '+236': 'Central African Republic',
      '+237': 'Cameroon',
      '+238': 'Cape Verde',
      '+239': 'São Tomé and Príncipe',
      '+240': 'Equatorial Guinea',
      '+241': 'Gabon',
      '+242': 'Republic of the Congo',
      '+243': 'Democratic Republic of the Congo',
      '+244': 'Angola',
      '+245': 'Guinea-Bissau',
      '+246': 'British Indian Ocean Territory',
      '+248': 'Seychelles',
      '+249': 'Sudan',
      '+250': 'Rwanda',
      '+251': 'Ethiopia',
      '+252': 'Somalia',
      '+253': 'Djibouti',
      '+254': 'Kenya',
      '+255': 'Tanzania',
      '+256': 'Uganda',
      '+257': 'Burundi',
      '+258': 'Mozambique',
      '+260': 'Zambia',
      '+261': 'Madagascar',
      '+262': 'Réunion',
      '+263': 'Zimbabwe',
      '+264': 'Namibia',
      '+265': 'Malawi',
      '+266': 'Lesotho',
      '+267': 'Botswana',
      '+268': 'Eswatini',
      '+269': 'Comoros',
      '+290': 'Saint Helena',
      '+291': 'Eritrea',
      '+297': 'Aruba',
      '+298': 'Faroe Islands',
      '+299': 'Greenland',
      '+350': 'Gibraltar',
      '+351': 'Portugal',
      '+352': 'Luxembourg',
      '+353': 'Ireland',
      '+354': 'Iceland',
      '+355': 'Albania',
      '+356': 'Malta',
      '+357': 'Cyprus',
      '+358': 'Finland',
      '+359': 'Bulgaria',
      '+370': 'Lithuania',
      '+371': 'Latvia',
      '+372': 'Estonia',
      '+373': 'Moldova',
      '+374': 'Armenia',
      '+375': 'Belarus',
      '+376': 'Andorra',
      '+377': 'Monaco',
      '+378': 'San Marino',
      '+379': 'Vatican City',
      '+380': 'Ukraine',
      '+381': 'Serbia',
      '+382': 'Montenegro',
      '+383': 'Kosovo',
      '+385': 'Croatia',
      '+386': 'Slovenia',
      '+387': 'Bosnia and Herzegovina',
      '+389': 'North Macedonia',
      '+420': 'Czech Republic',
      '+421': 'Slovakia',
      '+423': 'Liechtenstein',
      '+500': 'Falkland Islands',
      '+501': 'Belize',
      '+502': 'Guatemala',
      '+503': 'El Salvador',
      '+504': 'Honduras',
      '+505': 'Nicaragua',
      '+506': 'Costa Rica',
      '+507': 'Panama',
      '+508': 'Saint Pierre and Miquelon',
      '+509': 'Haiti',
      '+590': 'Guadeloupe',
      '+591': 'Bolivia',
      '+592': 'Guyana',
      '+593': 'Ecuador',
      '+594': 'French Guiana',
      '+595': 'Paraguay',
      '+596': 'Martinique',
      '+597': 'Suriname',
      '+598': 'Uruguay',
      '+599': 'Caribbean Netherlands',
      '+670': 'Timor-Leste',
      '+672': 'Australian External Territories',
      '+673': 'Brunei',
      '+674': 'Nauru',
      '+675': 'Papua New Guinea',
      '+676': 'Tonga',
      '+677': 'Solomon Islands',
      '+678': 'Vanuatu',
      '+679': 'Fiji',
      '+680': 'Palau',
      '+681': 'Wallis and Futuna',
      '+682': 'Cook Islands',
      '+683': 'Niue',
      '+685': 'Samoa',
      '+686': 'Kiribati',
      '+687': 'New Caledonia',
      '+688': 'Tuvalu',
      '+689': 'French Polynesia',
      '+690': 'Tokelau',
      '+691': 'Micronesia',
      '+692': 'Marshall Islands',
      '+850': 'North Korea',
      '+852': 'Hong Kong',
      '+853': 'Macau',
      '+855': 'Cambodia',
      '+856': 'Laos',
      '+880': 'Bangladesh',
      '+886': 'Taiwan',
      '+960': 'Maldives',
      '+961': 'Lebanon',
      '+962': 'Jordan',
      '+963': 'Syria',
      '+964': 'Iraq',
      '+965': 'Kuwait',
      '+966': 'Saudi Arabia',
      '+967': 'Yemen',
      '+968': 'Oman',
      '+970': 'Palestine',
      '+971': 'United Arab Emirates',
      '+972': 'Israel',
      '+973': 'Bahrain',
      '+974': 'Qatar',
      '+975': 'Bhutan',
      '+976': 'Mongolia',
      '+977': 'Nepal',
      '+992': 'Tajikistan',
      '+993': 'Turkmenistan',
      '+994': 'Azerbaijan',
      '+995': 'Georgia',
      '+996': 'Kyrgyzstan',
      '+998': 'Uzbekistan',
    },
  },

  //German
  de: {
    title: 'Chipsytok',
    login: 'Anmelden',
    signup: 'Registrieren',
    firstName: 'Vorname',
    lastName: 'Nachname',
    username: 'Benutzername',
    password: 'Passwort',
    confirmPassword: 'Passwort bestätigen',
    email: 'E-Mail',
    phoneNumber: 'Telefonnummer',
    forgotPassword: 'Passwort vergessen?',
    noAccount: 'Noch kein Konto?',
    haveAccount: 'Bereits ein Konto?',
    chooseLanguage: 'Sprache wählen',
    sendResetLink: 'Link senden',
    cancel: 'Abbrechen',
    resetPassword: 'Passwort zurücksetzen',
    viaEmail: 'Per E-Mail',
    viaUsername: 'Per Benutzername',
    verificationTitle: 'Geben Sie den 5-stelligen Bestätigungscode ein',
    verify: 'Bestätigen',
    verificationFailed: 'Bestätigung fehlgeschlagen',
    placeholderPhone: 'Telefonnummer, Benutzername oder E-Mail',
    errors: {
      usernameRequired: 'Benutzername ist erforderlich',
      passwordRequired: 'Passwort ist erforderlich',
      emailRequired: 'E-Mail ist erforderlich',
      passwordsMismatch: 'Passwörter stimmen nicht überein',
      generalError: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
    },
    countries: {
      '+1': 'USA',
      '+7': 'Russland / Kasachstan',
      '+20': 'Ägypten',
      '+27': 'Südafrika',
      '+30': 'Griechenland',
      '+31': 'Niederlande',
      '+32': 'Belgien',
      '+33': 'Frankreich',
      '+34': 'Spanien',
      '+36': 'Ungarn',
      '+39': 'Italien',
      '+40': 'Rumänien',
      '+41': 'Schweiz',
      '+43': 'Österreich',
      '+44': 'Vereinigtes Königreich',
      '+45': 'Dänemark',
      '+46': 'Schweden',
      '+47': 'Norwegen',
      '+48': 'Polen',
      '+49': 'Deutschland',
      '+51': 'Peru',
      '+52': 'Mexiko',
      '+53': 'Kuba',
      '+54': 'Argentinien',
      '+55': 'Brasilien',
      '+56': 'Chile',
      '+57': 'Kolumbien',
      '+58': 'Venezuela',
      '+60': 'Malaysia',
      '+61': 'Australien',
      '+62': 'Indonesien',
      '+63': 'Philippinen',
      '+64': 'Neuseeland',
      '+65': 'Singapur',
      '+66': 'Thailand',
      '+81': 'Japan',
      '+82': 'Südkorea',
      '+84': 'Vietnam',
      '+86': 'China',
      '+90': 'Türkei',
      '+91': 'Indien',
      '+92': 'Pakistan',
      '+93': 'Afghanistan',
      '+94': 'Sri Lanka',
      '+95': 'Myanmar',
      '+98': 'Iran',
      '+211': 'Südsudan',
      '+212': 'Marokko',
      '+213': 'Algerien',
      '+216': 'Tunesien',
      '+218': 'Libyen',
      '+220': 'Gambia',
      '+221': 'Senegal',
      '+222': 'Mauretanien',
      '+223': 'Mali',
      '+224': 'Guinea',
      '+225': 'Elfenbeinküste',
      '+226': 'Burkina Faso',
      '+227': 'Niger',
      '+228': 'Togo',
      '+229': 'Benin',
      '+230': 'Mauritius',
      '+231': 'Liberia',
      '+232': 'Sierra Leone',
      '+233': 'Ghana',
      '+234': 'Nigeria',
      '+235': 'Tschad',
      '+236': 'Zentralafrikanische Republik',
      '+237': 'Kamerun',
      '+238': 'Kap Verde',
      '+239': 'São Tomé und Príncipe',
      '+240': 'Äquatorialguinea',
      '+241': 'Gabun',
      '+242': 'Republik Kongo',
      '+243': 'Demokratische Republik Kongo',
      '+244': 'Angola',
      '+245': 'Guinea-Bissau',
      '+246': 'Britisches Territorium im Indischen Ozean',
      '+248': 'Seychellen',
      '+249': 'Sudan',
      '+250': 'Ruanda',
      '+251': 'Äthiopien',
      '+252': 'Somalia',
      '+253': 'Dschibuti',
      '+254': 'Kenia',
      '+255': 'Tansania',
      '+256': 'Uganda',
      '+257': 'Burundi',
      '+258': 'Mosambik',
      '+260': 'Sambia',
      '+261': 'Madagaskar',
      '+262': 'Réunion',
      '+263': 'Simbabwe',
      '+264': 'Namibia',
      '+265': 'Malawi',
      '+266': 'Lesotho',
      '+267': 'Botswana',
      '+268': 'Eswatini',
      '+269': 'Komoren',
      '+290': 'St. Helena',
      '+291': 'Eritrea',
      '+297': 'Aruba',
      '+298': 'Färöer-Inseln',
      '+299': 'Grönland',
      '+350': 'Gibraltar',
      '+351': 'Portugal',
      '+352': 'Luxemburg',
      '+353': 'Irland',
      '+354': 'Island',
      '+355': 'Albanien',
      '+356': 'Malta',
      '+357': 'Zypern',
      '+358': 'Finnland',
      '+359': 'Bulgarien',
      '+370': 'Litauen',
      '+371': 'Lettland',
      '+372': 'Estland',
      '+373': 'Moldawien',
      '+374': 'Armenien',
      '+375': 'Weißrussland',
      '+376': 'Andorra',
      '+377': 'Monaco',
      '+378': 'San Marino',
      '+379': 'Vatikanstadt',
      '+380': 'Ukraine',
      '+381': 'Serbien',
      '+382': 'Montenegro',
      '+383': 'Kosovo',
      '+385': 'Kroatien',
      '+386': 'Slowenien',
      '+387': 'Bosnien und Herzegowina',
      '+389': 'Nordmazedonien',
      '+420': 'Tschechien',
      '+421': 'Slowakei',
      '+423': 'Liechtenstein',
      '+500': 'Falklandinseln',
      '+501': 'Belize',
      '+502': 'Guatemala',
      '+503': 'El Salvador',
      '+504': 'Honduras',
      '+505': 'Nicaragua',
      '+506': 'Costa Rica',
      '+507': 'Panama',
      '+508': 'Saint-Pierre und Miquelon',
      '+509': 'Haiti',
      '+590': 'Guadeloupe',
      '+591': 'Bolivien',
      '+592': 'Guyana',
      '+593': 'Ecuador',
      '+594': 'Französisch-Guayana',
      '+595': 'Paraguay',
      '+596': 'Martinique',
      '+597': 'Suriname',
      '+598': 'Uruguay',
      '+599': 'Karibische Niederlande',
      '+670': 'Osttimor',
      '+672': 'Australische Außengebiete',
      '+673': 'Brunei',
      '+674': 'Nauru',
      '+675': 'Papua-Neuguinea',
      '+676': 'Tonga',
      '+677': 'Salomonen',
      '+678': 'Vanuatu',
      '+679': 'Fidschi',
      '+680': 'Palau',
      '+681': 'Wallis und Futuna',
      '+682': 'Cookinseln',
      '+683': 'Niue',
      '+685': 'Samoa',
      '+686': 'Kiribati',
      '+687': 'Neukaledonien',
      '+688': 'Tuvalu',
      '+689': 'Französisch-Polynesien',
      '+690': 'Tokelau',
      '+691': 'Mikronesien',
      '+692': 'Marshallinseln',
      '+850': 'Nordkorea',
      '+852': 'Hongkong',
      '+853': 'Macau',
      '+855': 'Kambodscha',
      '+856': 'Laos',
      '+880': 'Bangladesch',
      '+886': 'Taiwan',
      '+960': 'Malediven',
      '+961': 'Libanon',
      '+962': 'Jordanien',
      '+963': 'Syrien',
      '+964': 'Irak',
      '+965': 'Kuwait',
      '+966': 'Saudi-Arabien',
      '+967': 'Jemen',
      '+968': 'Oman',
      '+970': 'Palästina',
      '+971': 'Vereinigte Arabische Emirate',
      '+972': 'Israel',
      '+973': 'Bahrain',
      '+974': 'Katar',
      '+975': 'Bhutan',
      '+976': 'Mongolei',
      '+977': 'Nepal',
      '+992': 'Tadschikistan',
      '+993': 'Turkmenistan',
      '+994': 'Aserbaidschan',
      '+995': 'Georgien',
      '+996': 'Kirgisistan',
      '+998': 'Usbekistan',
    },
  },

  //French
  fr: {
    title: 'Chipsytok',
    login: 'Se connecter',
    signup: "S'inscrire",
    firstName: 'Prénom',
    lastName: 'Nom de famille',
    username: "Nom d'utilisateur",
    password: 'Mot de passe',
    confirmPassword: 'Confirmez le mot de passe',
    email: 'E-mail',
    phoneNumber: 'Numéro de téléphone',
    forgotPassword: 'Mot de passe oublié ?',
    noAccount: "Vous n'avez pas de compte ?",
    haveAccount: 'Vous avez déjà un compte ?',
    chooseLanguage: 'Choisissez votre langue',
    sendResetLink: 'Envoyer le lien de réinitialisation',
    cancel: 'Annuler',
    resetPassword: 'Réinitialiser votre mot de passe',
    viaEmail: 'Par e-mail',
    viaUsername: "Par nom d'utilisateur",
    verificationTitle: 'Entrez le code de vérification à 5 chiffres',
    verify: 'Vérifier',
    verificationFailed: 'Échec de la vérification',
    placeholderPhone: 'Numéro de téléphone, nom d’utilisateur ou e-mail',
    errors: {
      usernameRequired: "Le nom d'utilisateur est requis",
      passwordRequired: 'Le mot de passe est requis',
      emailRequired: "L'e-mail est requis",
      passwordsMismatch: 'Les mots de passe ne correspondent pas',
      generalError: 'Une erreur s’est produite. Veuillez réessayer.',
    },
    countries: {
      '+1': 'États-Unis / Canada',
      '+7': 'Russie / Kazakhstan',
      '+20': 'Égypte',
      '+27': 'Afrique du Sud',
      '+30': 'Grèce',
      '+31': 'Pays-Bas',
      '+32': 'Belgique',
      '+33': 'France',
      '+34': 'Espagne',
      '+36': 'Hongrie',
      '+39': 'Italie',
      '+40': 'Roumanie',
      '+41': 'Suisse',
      '+43': 'Autriche',
      '+44': 'Royaume-Uni',
      '+45': 'Danemark',
      '+46': 'Suède',
      '+47': 'Norvège',
      '+48': 'Pologne',
      '+49': 'Allemagne',
      '+51': 'Pérou',
      '+52': 'Mexique',
      '+53': 'Cuba',
      '+54': 'Argentine',
      '+55': 'Brésil',
      '+56': 'Chili',
      '+57': 'Colombie',
      '+58': 'Venezuela',
      '+60': 'Malaisie',
      '+61': 'Australie',
      '+62': 'Indonésie',
      '+63': 'Philippines',
      '+64': 'Nouvelle-Zélande',
      '+65': 'Singapour',
      '+66': 'Thaïlande',
      '+81': 'Japon',
      '+82': 'Corée du Sud',
      '+84': 'Viêt Nam',
      '+86': 'Chine',
      '+90': 'Turquie',
      '+91': 'Inde',
      '+92': 'Pakistan',
      '+93': 'Afghanistan',
      '+94': 'Sri Lanka',
      '+95': 'Myanmar',
      '+98': 'Iran',
      '+211': 'Soudan du Sud',
      '+212': 'Maroc',
      '+213': 'Algérie',
      '+216': 'Tunisie',
      '+218': 'Libye',
      '+220': 'Gambie',
      '+221': 'Sénégal',
      '+222': 'Mauritanie',
      '+223': 'Mali',
      '+224': 'Guinée',
      '+225': 'Côte d’Ivoire',
      '+226': 'Burkina Faso',
      '+227': 'Niger',
      '+228': 'Togo',
      '+229': 'Bénin',
      '+230': 'Maurice',
      '+231': 'Libéria',
      '+232': 'Sierra Leone',
      '+233': 'Ghana',
      '+234': 'Nigéria',
      '+235': 'Tchad',
      '+236': 'République centrafricaine',
      '+237': 'Cameroun',
      '+238': 'Cap-Vert',
      '+239': 'Sao Tomé-et-Principe',
      '+240': 'Guinée équatoriale',
      '+241': 'Gabon',
      '+242': 'République du Congo',
      '+243': 'République démocratique du Congo',
      '+244': 'Angola',
      '+245': 'Guinée-Bissau',
      '+246': 'Territoire britannique de l’océan Indien',
      '+248': 'Seychelles',
      '+249': 'Soudan',
      '+250': 'Rwanda',
      '+251': 'Éthiopie',
      '+252': 'Somalie',
      '+253': 'Djibouti',
      '+254': 'Kenya',
      '+255': 'Tanzanie',
      '+256': 'Ouganda',
      '+257': 'Burundi',
      '+258': 'Mozambique',
      '+260': 'Zambie',
      '+261': 'Madagascar',
      '+262': 'Réunion',
      '+263': 'Zimbabwe',
      '+264': 'Namibie',
      '+265': 'Malawi',
      '+266': 'Lesotho',
      '+267': 'Botswana',
      '+268': 'Eswatini',
      '+269': 'Comores',
      '+290': 'Sainte-Hélène',
      '+291': 'Érythrée',
      '+297': 'Aruba',
      '+298': 'Îles Féroé',
      '+299': 'Groenland',
      '+350': 'Gibraltar',
      '+351': 'Portugal',
      '+352': 'Luxembourg',
      '+353': 'Irlande',
      '+354': 'Islande',
      '+355': 'Albanie',
      '+356': 'Malte',
      '+357': 'Chypre',
      '+358': 'Finlande',
      '+359': 'Bulgarie',
      '+370': 'Lituanie',
      '+371': 'Lettonie',
      '+372': 'Estonie',
      '+373': 'Moldavie',
      '+374': 'Arménie',
      '+375': 'Biélorussie',
      '+376': 'Andorre',
      '+377': 'Monaco',
      '+378': 'Saint-Marin',
      '+379': 'Vatican',
      '+380': 'Ukraine',
      '+381': 'Serbie',
      '+382': 'Monténégro',
      '+383': 'Kosovo',
      '+385': 'Croatie',
      '+386': 'Slovénie',
      '+387': 'Bosnie-Herzégovine',
      '+389': 'Macédoine du Nord',
      '+420': 'Tchéquie',
      '+421': 'Slovaquie',
      '+423': 'Liechtenstein',
      '+500': 'Îles Malouines',
      '+501': 'Belize',
      '+502': 'Guatemala',
      '+503': 'Salvador',
      '+504': 'Honduras',
      '+505': 'Nicaragua',
      '+506': 'Costa Rica',
      '+507': 'Panama',
      '+508': 'Saint-Pierre-et-Miquelon',
      '+509': 'Haïti',
      '+590': 'Guadeloupe',
      '+591': 'Bolivie',
      '+592': 'Guyana',
      '+593': 'Équateur',
      '+594': 'Guyane française',
      '+595': 'Paraguay',
      '+596': 'Martinique',
      '+597': 'Suriname',
      '+598': 'Uruguay',
      '+599': 'Pays-Bas caribéens',
      '+670': 'Timor oriental',
      '+672': 'Territoires extérieurs australiens',
      '+673': 'Brunei',
      '+674': 'Nauru',
      '+675': 'Papouasie-Nouvelle-Guinée',
      '+676': 'Tonga',
      '+677': 'Îles Salomon',
      '+678': 'Vanuatu',
      '+679': 'Fidji',
      '+680': 'Palaos',
      '+681': 'Wallis-et-Futuna',
      '+682': 'Îles Cook',
      '+683': 'Niue',
      '+685': 'Samoa',
      '+686': 'Kiribati',
      '+687': 'Nouvelle-Calédonie',
      '+688': 'Tuvalu',
      '+689': 'Polynésie française',
      '+690': 'Tokelau',
      '+691': 'Micronésie',
      '+692': 'Îles Marshall',
      '+850': 'Corée du Nord',
      '+852': 'Hong Kong',
      '+853': 'Macao',
      '+855': 'Cambodge',
      '+856': 'Laos',
      '+880': 'Bangladesh',
      '+886': 'Taïwan',
      '+960': 'Maldives',
      '+961': 'Liban',
      '+962': 'Jordanie',
      '+963': 'Syrie',
      '+964': 'Irak',
      '+965': 'Koweït',
      '+966': 'Arabie saoudite',
      '+967': 'Yémen',
      '+968': 'Oman',
      '+970': 'Palestine',
      '+971': 'Émirats arabes unis',
      '+972': 'Israël',
      '+973': 'Bahreïn',
      '+974': 'Qatar',
      '+975': 'Bhoutan',
      '+976': 'Mongolie',
      '+977': 'Népal',
      '+992': 'Tadjikistan',
      '+993': 'Turkménistan',
      '+994': 'Azerbaïdjan',
      '+995': 'Géorgie',
      '+996': 'Kirghizistan',
      '+998': 'Ouzbékistan',
    },

  },

  //Italian
  it: {
    title: 'Chipsytok',
    login: 'Accedi',
    signup: 'Registrati',
    firstName: 'Nome',
    lastName: 'Cognome',
    username: 'Nome utente',
    password: 'Password',
    confirmPassword: 'Conferma password',
    email: 'Email',
    phoneNumber: 'Numero di telefono',
    forgotPassword: 'Password dimenticata?',
    noAccount: 'Non hai un account?',
    haveAccount: 'Hai già un account?',
    chooseLanguage: 'Scegli la tua lingua',
    sendResetLink: 'Invia link di reset',
    cancel: 'Annulla',
    resetPassword: 'Reimposta la password',
    viaEmail: 'Via Email',
    viaUsername: 'Via Nome utente',
    verificationTitle: 'Inserisci il codice di verifica a 5 cifre',
    verify: 'Verifica',
    verificationFailed: 'Verifica fallita',
    placeholderPhone: 'Numero di telefono, nome utente o email',
    errors: {
      usernameRequired: "Il nome utente è obbligatorio",
      passwordRequired: 'La password è obbligatoria',
      emailRequired: "L'email è obbligatoria",
      passwordsMismatch: 'Le password non corrispondono',
      generalError: 'Si è verificato un errore. Riprova.',
    },
    countries: {
      '+1': 'Stati Uniti / Canada',
      '+7': 'Russia / Kazakistan',
      '+20': 'Egitto',
      '+27': 'Sudafrica',
      '+30': 'Grecia',
      '+31': 'Paesi Bassi',
      '+32': 'Belgio',
      '+33': 'Francia',
      '+34': 'Spagna',
      '+36': 'Ungheria',
      '+39': 'Italia',
      '+40': 'Romania',
      '+41': 'Svizzera',
      '+43': 'Austria',
      '+44': 'Regno Unito',
      '+45': 'Danimarca',
      '+46': 'Svezia',
      '+47': 'Norvegia',
      '+48': 'Polonia',
      '+49': 'Germania',
      '+51': 'Perù',
      '+52': 'Messico',
      '+53': 'Cuba',
      '+54': 'Argentina',
      '+55': 'Brasile',
      '+56': 'Cile',
      '+57': 'Colombia',
      '+58': 'Venezuela',
      '+60': 'Malesia',
      '+61': 'Australia',
      '+62': 'Indonesia',
      '+63': 'Filippine',
      '+64': 'Nuova Zelanda',
      '+65': 'Singapore',
      '+66': 'Thailandia',
      '+81': 'Giappone',
      '+82': 'Corea del Sud',
      '+84': 'Vietnam',
      '+86': 'Cina',
      '+90': 'Turchia',
      '+91': 'India',
      '+92': 'Pakistan',
      '+93': 'Afghanistan',
      '+94': 'Sri Lanka',
      '+95': 'Myanmar',
      '+98': 'Iran',
      '+211': 'Sud Sudan',
      '+212': 'Marocco',
      '+213': 'Algeria',
      '+216': 'Tunisia',
      '+218': 'Libia',
      '+220': 'Gambia',
      '+221': 'Senegal',
      '+222': 'Mauritania',
      '+223': 'Mali',
      '+224': 'Guinea',
      '+225': 'Costa d’Avorio',
      '+226': 'Burkina Faso',
      '+227': 'Niger',
      '+228': 'Togo',
      '+229': 'Benin',
      '+230': 'Mauritius',
      '+231': 'Liberia',
      '+232': 'Sierra Leone',
      '+233': 'Ghana',
      '+234': 'Nigeria',
      '+235': 'Ciad',
      '+236': 'Repubblica Centrafricana',
      '+237': 'Camerun',
      '+238': 'Capo Verde',
      '+239': 'São Tomé e Príncipe',
      '+240': 'Guinea Equatoriale',
      '+241': 'Gabon',
      '+242': 'Repubblica del Congo',
      '+243': 'Repubblica Democratica del Congo',
      '+244': 'Angola',
      '+245': 'Guinea-Bissau',
      '+246': 'Territorio britannico dell’oceano Indiano',
      '+248': 'Seychelles',
      '+249': 'Sudan',
      '+250': 'Ruanda',
      '+251': 'Etiopia',
      '+252': 'Somalia',
      '+253': 'Gibuti',
      '+254': 'Kenya',
      '+255': 'Tanzania',
      '+256': 'Uganda',
      '+257': 'Burundi',
      '+258': 'Mozambico',
      '+260': 'Zambia',
      '+261': 'Madagascar',
      '+262': 'Riunione',
      '+263': 'Zimbabwe',
      '+264': 'Namibia',
      '+265': 'Malawi',
      '+266': 'Lesotho',
      '+267': 'Botswana',
      '+268': 'Eswatini',
      '+269': 'Comore',
      '+290': 'Sant’Elena',
      '+291': 'Eritrea',
      '+297': 'Aruba',
      '+298': 'Isole Faroe',
      '+299': 'Groenlandia',
      '+350': 'Gibilterra',
      '+351': 'Portogallo',
      '+352': 'Lussemburgo',
      '+353': 'Irlanda',
      '+354': 'Islanda',
      '+355': 'Albania',
      '+356': 'Malta',
      '+357': 'Cipro',
      '+358': 'Finlandia',
      '+359': 'Bulgaria',
      '+370': 'Lituania',
      '+371': 'Lettonia',
      '+372': 'Estonia',
      '+373': 'Moldavia',
      '+374': 'Armenia',
      '+375': 'Bielorussia',
      '+376': 'Andorra',
      '+377': 'Monaco',
      '+378': 'San Marino',
      '+379': 'Città del Vaticano',
      '+380': 'Ucraina',
      '+381': 'Serbia',
      '+382': 'Montenegro',
      '+383': 'Kosovo',
      '+385': 'Croazia',
      '+386': 'Slovenia',
      '+387': 'Bosnia ed Erzegovina',
      '+389': 'Macedonia del Nord',
      '+420': 'Repubblica Ceca',
      '+421': 'Slovacchia',
      '+423': 'Liechtenstein',
      '+500': 'Isole Falkland',
      '+501': 'Belize',
      '+502': 'Guatemala',
      '+503': 'El Salvador',
      '+504': 'Honduras',
      '+505': 'Nicaragua',
      '+506': 'Costa Rica',
      '+507': 'Panama',
      '+508': 'Saint-Pierre e Miquelon',
      '+509': 'Haiti',
      '+590': 'Guadalupa',
      '+591': 'Bolivia',
      '+592': 'Guyana',
      '+593': 'Ecuador',
      '+594': 'Guyana francese',
      '+595': 'Paraguay',
      '+596': 'Martinica',
      '+597': 'Suriname',
      '+598': 'Uruguay',
      '+599': 'Caraibi olandesi',
      '+670': 'Timor Est',
      '+672': 'Territori esterni australiani',
      '+673': 'Brunei',
      '+674': 'Nauru',
      '+675': 'Papua Nuova Guinea',
      '+676': 'Tonga',
      '+677': 'Isole Salomone',
      '+678': 'Vanuatu',
      '+679': 'Figi',
      '+680': 'Palau',
      '+681': 'Wallis e Futuna',
      '+682': 'Isole Cook',
      '+683': 'Niue',
      '+685': 'Samoa',
      '+686': 'Kiribati',
      '+687': 'Nuova Caledonia',
      '+688': 'Tuvalu',
      '+689': 'Polinesia francese',
      '+690': 'Tokelau',
      '+691': 'Micronesia',
      '+692': 'Isole Marshall',
      '+850': 'Corea del Nord',
      '+852': 'Hong Kong',
      '+853': 'Macao',
      '+855': 'Cambogia',
      '+856': 'Laos',
      '+880': 'Bangladesh',
      '+886': 'Taiwan',
      '+960': 'Maldive',
      '+961': 'Libano',
      '+962': 'Giordania',
      '+963': 'Siria',
      '+964': 'Iraq',
      '+965': 'Kuwait',
      '+966': 'Arabia Saudita',
      '+967': 'Yemen',
      '+968': 'Oman',
      '+970': 'Palestina',
      '+971': 'Emirati Arabi Uniti',
      '+972': 'Israele',
      '+973': 'Bahrein',
      '+974': 'Qatar',
      '+975': 'Bhutan',
      '+976': 'Mongolia',
      '+977': 'Nepal',
      '+992': 'Tagikistan',
      '+993': 'Turkmenistan',
      '+994': 'Azerbaigian',
      '+995': 'Georgia',
      '+996': 'Kirghizistan',
      '+998': 'Uzbekistan',
    },

  },
  //Spanish
  es: {
    title: 'Chipsytok',
    login: 'Iniciar sesión',
    signup: 'Registrarse',
    firstName: 'Nombre',
    lastName: 'Apellido',
    username: 'Nombre de usuario',
    password: 'Contraseña',
    confirmPassword: 'Confirmar contraseña',
    email: 'Correo electrónico',
    phoneNumber: 'Número de teléfono',
    forgotPassword: '¿Olvidaste tu contraseña?',
    noAccount: '¿No tienes una cuenta?',
    haveAccount: '¿Ya tienes una cuenta?',
    chooseLanguage: 'Elige tu idioma',
    sendResetLink: 'Enviar enlace de restablecimiento',
    cancel: 'Cancelar',
    resetPassword: 'Restablecer tu contraseña',
    viaEmail: 'Vía correo electrónico',
    viaUsername: 'Vía nombre de usuario',
    verificationTitle: 'Introduce el código de verificación de 5 dígitos',
    verify: 'Verificar',
    verificationFailed: 'La verificación falló',
    placeholderPhone: 'Número de teléfono, nombre de usuario o correo electrónico',
    errors: {
      usernameRequired: 'El nombre de usuario es obligatorio',
      passwordRequired: 'La contraseña es obligatoria',
      emailRequired: 'El correo electrónico es obligatorio',
      passwordsMismatch: 'Las contraseñas no coinciden',
      generalError: 'Ocurrió un error. Por favor, inténtalo de nuevo.',
    },
    countries: {
      '+1': 'Estados Unidos / Canadá',
      '+7': 'Rusia / Kazajistán',
      '+20': 'Egipto',
      '+27': 'Sudáfrica',
      '+30': 'Grecia',
      '+31': 'Países Bajos',
      '+32': 'Bélgica',
      '+33': 'Francia',
      '+34': 'España',
      '+36': 'Hungría',
      '+39': 'Italia',
      '+40': 'Rumanía',
      '+41': 'Suiza',
      '+43': 'Austria',
      '+44': 'Reino Unido',
      '+45': 'Dinamarca',
      '+46': 'Suecia',
      '+47': 'Noruega',
      '+48': 'Polonia',
      '+49': 'Alemania',
      '+51': 'Perú',
      '+52': 'México',
      '+53': 'Cuba',
      '+54': 'Argentina',
      '+55': 'Brasil',
      '+56': 'Chile',
      '+57': 'Colombia',
      '+58': 'Venezuela',
      '+60': 'Malasia',
      '+61': 'Australia',
      '+62': 'Indonesia',
      '+63': 'Filipinas',
      '+64': 'Nueva Zelanda',
      '+65': 'Singapur',
      '+66': 'Tailandia',
      '+81': 'Japón',
      '+82': 'Corea del Sur',
      '+84': 'Vietnam',
      '+86': 'China',
      '+90': 'Turquía',
      '+91': 'India',
      '+92': 'Pakistán',
      '+93': 'Afganistán',
      '+94': 'Sri Lanka',
      '+95': 'Myanmar',
      '+98': 'Irán',
      '+211': 'Sudán del Sur',
      '+212': 'Marruecos',
      '+213': 'Argelia',
      '+216': 'Túnez',
      '+218': 'Libia',
      '+220': 'Gambia',
      '+221': 'Senegal',
      '+222': 'Mauritania',
      '+223': 'Malí',
      '+224': 'Guinea',
      '+225': 'Costa de Marfil',
      '+226': 'Burkina Faso',
      '+227': 'Níger',
      '+228': 'Togo',
      '+229': 'Benín',
      '+230': 'Mauricio',
      '+231': 'Liberia',
      '+232': 'Sierra Leona',
      '+233': 'Ghana',
      '+234': 'Nigeria',
      '+235': 'Chad',
      '+236': 'República Centroafricana',
      '+237': 'Camerún',
      '+238': 'Cabo Verde',
      '+239': 'Santo Tomé y Príncipe',
      '+240': 'Guinea Ecuatorial',
      '+241': 'Gabón',
      '+242': 'República del Congo',
      '+243': 'República Democrática del Congo',
      '+244': 'Angola',
      '+245': 'Guinea-Bisáu',
      '+248': 'Seychelles',
      '+249': 'Sudán',
      '+250': 'Ruanda',
      '+251': 'Etiopía',
      '+252': 'Somalia',
      '+253': 'Yibuti',
      '+254': 'Kenia',
      '+255': 'Tanzania',
      '+256': 'Uganda',
      '+257': 'Burundi',
      '+258': 'Mozambique',
      '+260': 'Zambia',
      '+261': 'Madagascar',
      '+262': 'Reunión',
      '+263': 'Zimbabue',
      '+264': 'Namibia',
      '+265': 'Malaui',
      '+266': 'Lesoto',
      '+267': 'Botsuana',
      '+268': 'Esuatini',
      '+269': 'Comoras',
      '+290': 'Santa Elena',
      '+291': 'Eritrea',
      '+297': 'Aruba',
      '+298': 'Islas Feroe',
      '+299': 'Groenlandia',
      '+350': 'Gibraltar',
      '+351': 'Portugal',
      '+352': 'Luxemburgo',
      '+353': 'Irlanda',
      '+354': 'Islandia',
      '+355': 'Albania',
      '+356': 'Malta',
      '+357': 'Chipre',
      '+358': 'Finlandia',
      '+359': 'Bulgaria',
      '+370': 'Lituania',
      '+371': 'Letonia',
      '+372': 'Estonia',
      '+373': 'Moldavia',
      '+374': 'Armenia',
      '+375': 'Bielorrusia',
      '+376': 'Andorra',
      '+377': 'Mónaco',
      '+378': 'San Marino',
      '+379': 'Ciudad del Vaticano',
      '+380': 'Ucrania',
      '+381': 'Serbia',
      '+382': 'Montenegro',
      '+383': 'Kosovo',
      '+385': 'Croacia',
      '+386': 'Eslovenia',
      '+387': 'Bosnia y Herzegovina',
      '+389': 'Macedonia del Norte',
      '+420': 'Chequia',
      '+421': 'Eslovaquia',
      '+423': 'Liechtenstein',
      '+500': 'Islas Malvinas',
      '+501': 'Belice',
      '+502': 'Guatemala',
      '+503': 'El Salvador',
      '+504': 'Honduras',
      '+505': 'Nicaragua',
      '+506': 'Costa Rica',
      '+507': 'Panamá',
      '+508': 'San Pedro y Miquelón',
      '+509': 'Haití',
      '+590': 'Guadalupe',
      '+591': 'Bolivia',
      '+592': 'Guyana',
      '+593': 'Ecuador',
      '+594': 'Guayana Francesa',
      '+595': 'Paraguay',
      '+596': 'Martinica',
      '+597': 'Surinam',
      '+598': 'Uruguay',
      '+599': 'Caribe Neerlandés',
      '+670': 'Timor Oriental',
      '+673': 'Brunéi',
      '+674': 'Nauru',
      '+675': 'Papúa Nueva Guinea',
      '+676': 'Tonga',
      '+677': 'Islas Salomón',
      '+678': 'Vanuatu',
      '+679': 'Fiyi',
      '+680': 'Palaos',
      '+681': 'Wallis y Futuna',
      '+682': 'Islas Cook',
      '+683': 'Niue',
      '+685': 'Samoa',
      '+686': 'Kiribati',
      '+687': 'Nueva Caledonia',
      '+688': 'Tuvalu',
      '+689': 'Polinesia Francesa',
      '+690': 'Tokelau',
      '+691': 'Micronesia',
      '+692': 'Islas Marshall',
      '+850': 'Corea del Norte',
      '+852': 'Hong Kong',
      '+853': 'Macao',
      '+855': 'Camboya',
      '+856': 'Laos',
      '+880': 'Bangladés',
      '+886': 'Taiwán',
      '+960': 'Maldivas',
      '+961': 'Líbano',
      '+962': 'Jordania',
      '+963': 'Siria',
      '+964': 'Irak',
      '+965': 'Kuwait',
      '+966': 'Arabia Saudita',
      '+967': 'Yemen',
      '+968': 'Omán',
      '+970': 'Palestina',
      '+971': 'Emiratos Árabes Unidos',
      '+972': 'Israel',
      '+973': 'Baréin',
      '+974': 'Catar',
      '+975': 'Bután',
      '+976': 'Mongolia',
      '+977': 'Nepal',
      '+992': 'Tayikistán',
      '+993': 'Turkmenistán',
      '+994': 'Azerbaiyán',
      '+995': 'Georgia',
      '+996': 'Kirguistán',
      '+998': 'Uzbekistán',
    },

  },
  //Chinese
  zh: {
    title: 'Chipsytok',
    login: '登录',
    signup: '注册',
    firstName: '名字',
    lastName: '姓氏',
    username: '用户名',
    password: '密码',
    confirmPassword: '确认密码',
    email: '电子邮件',
    phoneNumber: '电话号码',
    forgotPassword: '忘记密码？',
    noAccount: '没有账户？',
    haveAccount: '已有账户？',
    chooseLanguage: '选择你的语言',
    sendResetLink: '发送重置链接',
    cancel: '取消',
    resetPassword: '重置你的密码',
    viaEmail: '通过电子邮件',
    viaUsername: '通过用户名',
    verificationTitle: '输入 5 位验证码',
    verify: '验证',
    verificationFailed: '验证失败',
    placeholderPhone: '电话号码，用户名或电子邮件',
    errors: {
      usernameRequired: '用户名是必填项',
      passwordRequired: '密码是必填项',
      emailRequired: '电子邮件是必填项',
      passwordsMismatch: '两次输入的密码不一致',
      generalError: '发生错误。请再试一次。',
    },
    countries: {
      '+1': '美国 / 加拿大',
      '+7': '俄罗斯 / 哈萨克斯坦',
      '+20': '埃及',
      '+27': '南非',
      '+30': '希腊',
      '+31': '荷兰',
      '+32': '比利时',
      '+33': '法国',
      '+34': '西班牙',
      '+36': '匈牙利',
      '+39': '意大利',
      '+40': '罗马尼亚',
      '+41': '瑞士',
      '+43': '奥地利',
      '+44': '英国',
      '+45': '丹麦',
      '+46': '瑞典',
      '+47': '挪威',
      '+48': '波兰',
      '+49': '德国',
      '+51': '秘鲁',
      '+52': '墨西哥',
      '+53': '古巴',
      '+54': '阿根廷',
      '+55': '巴西',
      '+56': '智利',
      '+57': '哥伦比亚',
      '+58': '委内瑞拉',
      '+60': '马来西亚',
      '+61': '澳大利亚',
      '+62': '印度尼西亚',
      '+63': '菲律宾',
      '+64': '新西兰',
      '+65': '新加坡',
      '+66': '泰国',
      '+81': '日本',
      '+82': '韩国',
      '+84': '越南',
      '+86': '中国',
      '+90': '土耳其',
      '+91': '印度',
      '+92': '巴基斯坦',
      '+93': '阿富汗',
      '+94': '斯里兰卡',
      '+95': '缅甸',
      '+98': '伊朗',
      '+211': '南苏丹',
      '+212': '摩洛哥',
      '+213': '阿尔及利亚',
      '+216': '突尼斯',
      '+218': '利比亚',
      '+220': '冈比亚',
      '+221': '塞内加尔',
      '+222': '毛里塔尼亚',
      '+223': '马里',
      '+224': '几内亚',
      '+225': '科特迪瓦',
      '+226': '布基纳法索',
      '+227': '尼日尔',
      '+228': '多哥',
      '+229': '贝宁',
      '+230': '毛里求斯',
      '+231': '利比里亚',
      '+232': '塞拉利昂',
      '+233': '加纳',
      '+234': '尼日利亚',
      '+235': '乍得',
      '+236': '中非共和国',
      '+237': '喀麦隆',
      '+238': '佛得角',
      '+239': '圣多美和普林西比',
      '+240': '赤道几内亚',
      '+241': '加蓬',
      '+242': '刚果（布）',
      '+243': '刚果（金）',
      '+244': '安哥拉',
      '+245': '几内亚比绍',
      '+248': '塞舌尔',
      '+249': '苏丹',
      '+250': '卢旺达',
      '+251': '埃塞俄比亚',
      '+252': '索马里',
      '+253': '吉布提',
      '+254': '肯尼亚',
      '+255': '坦桑尼亚',
      '+256': '乌干达',
      '+257': '布隆迪',
      '+258': '莫桑比克',
      '+260': '赞比亚',
      '+261': '马达加斯加',
      '+262': '留尼汪',
      '+263': '津巴布韦',
      '+264': '纳米比亚',
      '+265': '马拉维',
      '+266': '莱索托',
      '+267': '博茨瓦纳',
      '+268': '斯威士兰',
      '+269': '科摩罗',
      '+290': '圣赫勒拿',
      '+291': '厄立特里亚',
      '+297': '阿鲁巴',
      '+298': '法罗群岛',
      '+299': '格陵兰',
      '+350': '直布罗陀',
      '+351': '葡萄牙',
      '+352': '卢森堡',
      '+353': '爱尔兰',
      '+354': '冰岛',
      '+355': '阿尔巴尼亚',
      '+356': '马耳他',
      '+357': '塞浦路斯',
      '+358': '芬兰',
      '+359': '保加利亚',
      '+370': '立陶宛',
      '+371': '拉脱维亚',
      '+372': '爱沙尼亚',
      '+373': '摩尔多瓦',
      '+374': '亚美尼亚',
      '+375': '白俄罗斯',
      '+376': '安道尔',
      '+377': '摩纳哥',
      '+378': '圣马力诺',
      '+379': '梵蒂冈',
      '+380': '乌克兰',
      '+381': '塞尔维亚',
      '+382': '黑山',
      '+383': '科索沃',
      '+385': '克罗地亚',
      '+386': '斯洛文尼亚',
      '+387': '波黑',
      '+389': '北马其顿',
      '+420': '捷克',
      '+421': '斯洛伐克',
      '+423': '列支敦士登',
      '+500': '福克兰群岛',
      '+501': '伯利兹',
      '+502': '危地马拉',
      '+503': '萨尔瓦多',
      '+504': '洪都拉斯',
      '+505': '尼加拉瓜',
      '+506': '哥斯达黎加',
      '+507': '巴拿马',
      '+508': '圣皮埃尔和密克隆',
      '+509': '海地',
      '+590': '瓜德罗普',
      '+591': '玻利维亚',
      '+592': '圭亚那',
      '+593': '厄瓜多尔',
      '+594': '法属圭亚那',
      '+595': '巴拉圭',
      '+596': '马提尼克',
      '+597': '苏里南',
      '+598': '乌拉圭',
      '+599': '荷属加勒比',
      '+670': '东帝汶',
      '+673': '文莱',
      '+674': '瑙鲁',
      '+675': '巴布亚新几内亚',
      '+676': '汤加',
      '+677': '所罗门群岛',
      '+678': '瓦努阿图',
      '+679': '斐济',
      '+680': '帕劳',
      '+681': '瓦利斯和富图纳',
      '+682': '库克群岛',
      '+683': '纽埃',
      '+685': '萨摩亚',
      '+686': '基里巴斯',
      '+687': '新喀里多尼亚',
      '+688': '图瓦卢',
      '+689': '法属波利尼西亚',
      '+690': '托克劳',
      '+691': '密克罗尼西亚',
      '+692': '马绍尔群岛',
      '+850': '朝鲜',
      '+852': '香港',
      '+853': '澳门',
      '+855': '柬埔寨',
      '+856': '老挝',
      '+880': '孟加拉国',
      '+886': '台湾',
      '+960': '马尔代夫',
      '+961': '黎巴嫩',
      '+962': '约旦',
      '+963': '叙利亚',
      '+964': '伊拉克',
      '+965': '科威特',
      '+966': '沙特阿拉伯',
      '+967': '也门',
      '+968': '阿曼',
      '+970': '巴勒斯坦',
      '+971': '阿联酋',
      '+972': '以色列',
      '+973': '巴林',
      '+974': '卡塔尔',
      '+975': '不丹',
      '+976': '蒙古',
      '+977': '尼泊尔',
      '+992': '塔吉克斯坦',
      '+993': '土库曼斯坦',
      '+994': '阿塞拜疆',
      '+995': '格鲁吉亚',
      '+996': '吉尔吉斯斯坦',
      '+998': '乌兹别克斯坦',
    },
  },
};


const englishNames = {
  en: 'English',
  de: 'German',
  fr: 'French',
  it: 'Italian',
  es: 'Spanish',
  zh: 'Chinese',
};


const selectedLanguage = ref(localStorage.getItem('language') || '');

function setLanguage(lang) {
  localStorage.setItem('language', lang);
  window.location.reload();
}


function t(key) {
  const lang = selectedLanguage.value || 'en';
  return (
    key
      .split('.')
      .reduce((o, i) => (o ? o[i] : null), languages[lang]) || key
  );
}

function getEnglishName(lang) {
  return englishNames[lang] || lang;
}


export function useLanguage() {
  return {
    languages,
    selectedLanguage,
    setLanguage,
    t,
    getEnglishName,
  };
}



