import { ref } from 'vue';

const languages = {
    en: {
      title: 'Chipsytok',
      login: 'Log in',
      signup: 'Sign up',
      firstName: 'First Name',
      lastName: 'Last Name',
      username: 'Username',
      password: 'Password',
      confirmPassword: 'Confirm Password',
      email: 'Email',
      phoneNumber: 'Phone Number',
      forgotPassword: 'Forgot password?',
      noAccount: "Don't have an account?",
      haveAccount: 'Already have an account?',
      chooseLanguage: 'Choose your language',
      sendResetLink: 'Send Reset Link',
      cancel: 'Cancel',
      resetPassword: 'Reset your password',
      viaEmail: 'Via Email',
      viaUsername: 'Via Username',
      verificationTitle: 'Enter 5-digit verification code',
      verify: 'Verify',
      verificationFailed: 'Verification failed',
      placeholderPhone: 'Phone number, username, or email',
      errors: {
        usernameRequired: 'Username is required',
        passwordRequired: 'Password is required',
        emailRequired: 'Email is required',
        passwordsMismatch: 'Passwords do not match',
        generalError: 'An error occurred. Please try again.',
      },
      countries: {
      '+1': 'United States',
      '+41': 'Switzerland',
      '+49': 'Germany',
      '+33': 'France',
      '+34': 'Spain',
      '+351': 'Portugal',
      '+423': 'Liechtenstein',
      '+43': 'Austria',
      '+48': 'Poland',
      '+39': 'Italy',
    },
      
    },
    de: {
      title: 'Chipsytok',
      login: 'Anmelden',
      signup: 'Registrieren',
      firstName: 'Vorname',
      lastName: 'Nachname',
      username: 'Benutzername',
      password: 'Passwort',
      confirmPassword: 'Passwort bestätigen',
      email: 'E-Mail',
      phoneNumber: 'Telefonnummer',
      forgotPassword: 'Passwort vergessen?',
      noAccount: 'Noch kein Konto?',
      haveAccount: 'Bereits ein Konto?',
      chooseLanguage: 'Sprache wählen',
      sendResetLink: 'Link senden',
      cancel: 'Abbrechen',
      resetPassword: 'Passwort zurücksetzen',
      viaEmail: 'Per E-Mail',
      viaUsername: 'Per Benutzername',
      verificationTitle: 'Geben Sie den 5-stelligen Bestätigungscode ein',
      verify: 'Bestätigen',
      verificationFailed: 'Bestätigung fehlgeschlagen',
      placeholderPhone: 'Telefonnummer, Benutzername oder E-Mail',
      errors: {
        usernameRequired: 'Benutzername ist erforderlich',
        passwordRequired: 'Passwort ist erforderlich',
        emailRequired: 'E-Mail ist erforderlich',
        passwordsMismatch: 'Passwörter stimmen nicht überein',
        generalError: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut.',
      },
       countries: {
      '+1': 'USA',
      '+41': 'Schweiz',
      '+49': 'Deutschland',
      '+33': 'Frankreich',
      '+34': 'Spanien',
      '+351': 'Portugal',
      '+423': 'Liechtenstein',
      '+43': 'Österreich',
      '+48': 'Polen',
      '+39': 'Italien',
    },
    },
    fr: {
      title: 'Chipsytok',
      login: 'Se connecter',
      signup: "S'inscrire",
      firstName: 'Prénom',
      lastName: 'Nom de famille',
      username: "Nom d'utilisateur",
      password: 'Mot de passe',
      confirmPassword: 'Confirmez le mot de passe',
      email: 'E-mail',
      phoneNumber: 'Numéro de téléphone',
      forgotPassword: 'Mot de passe oublié ?',
      noAccount: "Vous n'avez pas de compte ?",
      haveAccount: 'Vous avez déjà un compte ?',
      chooseLanguage: 'Choisissez votre langue',
      sendResetLink: 'Envoyer le lien de réinitialisation',
      cancel: 'Annuler',
      resetPassword: 'Réinitialiser votre mot de passe',
      viaEmail: 'Par e-mail',
      viaUsername: "Par nom d'utilisateur",
      verificationTitle: 'Entrez le code de vérification à 5 chiffres',
      verify: 'Vérifier',
      verificationFailed: 'Échec de la vérification',
      placeholderPhone: 'Numéro de téléphone, nom d’utilisateur ou e-mail',
      errors: {
        usernameRequired: "Le nom d'utilisateur est requis",
        passwordRequired: 'Le mot de passe est requis',
        emailRequired: "L'e-mail est requis",
        passwordsMismatch: 'Les mots de passe ne correspondent pas',
        generalError: 'Une erreur s’est produite. Veuillez réessayer.',
      },
      countries: {
      '+1': 'États-Unis',
      '+41': 'Suisse',
      '+49': 'Allemagne',
      '+33': 'France',
      '+34': 'Espagne',
      '+351': 'Portugal',
      '+423': 'Liechtenstein',
      '+43': 'Autriche',
      '+48': 'Pologne',
      '+39': 'Italie',
    },
    },
    it: {
      title: 'Chipsytok',
      login: 'Accedi',
      signup: 'Registrati',
      firstName: 'Nome',
      lastName: 'Cognome',
      username: 'Nome utente',
      password: 'Password',
      confirmPassword: 'Conferma password',
      email: 'Email',
      phoneNumber: 'Numero di telefono',
      forgotPassword: 'Password dimenticata?',
      noAccount: 'Non hai un account?',
      haveAccount: 'Hai già un account?',
      chooseLanguage: 'Scegli la tua lingua',
      sendResetLink: 'Invia link di reset',
      cancel: 'Annulla',
      resetPassword: 'Reimposta la password',
      viaEmail: 'Via Email',
      viaUsername: 'Via Nome utente',
      verificationTitle: 'Inserisci il codice di verifica a 5 cifre',
      verify: 'Verifica',
      verificationFailed: 'Verifica fallita',
      placeholderPhone: 'Numero di telefono, nome utente o email',
      errors: {
        usernameRequired: "Il nome utente è obbligatorio",
        passwordRequired: 'La password è obbligatoria',
        emailRequired: "L'email è obbligatoria",
        passwordsMismatch: 'Le password non corrispondono',
        generalError: 'Si è verificato un errore. Riprova.',
      },
       countries: {
      '+1': 'Stati Uniti',
      '+41': 'Svizzera',
      '+49': 'Germania',
      '+33': 'Francia',
      '+34': 'Spagna',
      '+351': 'Portogallo',
      '+423': 'Liechtenstein',
      '+43': 'Austria',
      '+48': 'Polonia',
      '+39': 'Italia',
    },
    },
    es: {
      title: 'Chipsytok',
      login: 'Iniciar sesión',
      signup: 'Registrarse',
      firstName: 'Nombre',
      lastName: 'Apellido',
      username: 'Nombre de usuario',
      password: 'Contraseña',
      confirmPassword: 'Confirmar contraseña',
      email: 'Correo electrónico',
      phoneNumber: 'Número de teléfono',
      forgotPassword: '¿Olvidaste tu contraseña?',
      noAccount: '¿No tienes una cuenta?',
      haveAccount: '¿Ya tienes una cuenta?',
      chooseLanguage: 'Elige tu idioma',
      sendResetLink: 'Enviar enlace de restablecimiento',
      cancel: 'Cancelar',
      resetPassword: 'Restablecer tu contraseña',
      viaEmail: 'Vía correo electrónico',
      viaUsername: 'Vía nombre de usuario',
      verificationTitle: 'Introduce el código de verificación de 5 dígitos',
      verify: 'Verificar',
      verificationFailed: 'La verificación falló',
      placeholderPhone: 'Número de teléfono, nombre de usuario o correo electrónico',
      errors: {
        usernameRequired: 'El nombre de usuario es obligatorio',
        passwordRequired: 'La contraseña es obligatoria',
        emailRequired: 'El correo electrónico es obligatorio',
        passwordsMismatch: 'Las contraseñas no coinciden',
        generalError: 'Ocurrió un error. Por favor, inténtalo de nuevo.',
      },
       countries: {
      '+1': 'Estados Unidos',
      '+41': 'Suiza',
      '+49': 'Alemania',
      '+33': 'Francia',
      '+34': 'España',
      '+351': 'Portugal',
      '+423': 'Liechtenstein',
      '+43': 'Austria',
      '+48': 'Polonia',
      '+39': 'Italia',
    },
    },
    zh: {
      title: 'Chipsytok',
      login: '登录',
      signup: '注册',
      firstName: '名字',
      lastName: '姓氏',
      username: '用户名',
      password: '密码',
      confirmPassword: '确认密码',
      email: '电子邮件',
      phoneNumber: '电话号码',
      forgotPassword: '忘记密码？',
      noAccount: '没有账户？',
      haveAccount: '已有账户？',
      chooseLanguage: '选择你的语言',
      sendResetLink: '发送重置链接',
      cancel: '取消',
      resetPassword: '重置你的密码',
      viaEmail: '通过电子邮件',
      viaUsername: '通过用户名',
      verificationTitle: '输入 5 位验证码',
      verify: '验证',
      verificationFailed: '验证失败',
      placeholderPhone: '电话号码，用户名或电子邮件',
      errors: {
        usernameRequired: '用户名是必填项',
        passwordRequired: '密码是必填项',
        emailRequired: '电子邮件是必填项',
        passwordsMismatch: '两次输入的密码不一致',
        generalError: '发生错误。请再试一次。',
      },
       countries: {
      '+1': '美国',
      '+41': '瑞士',
      '+49': '德国',
      '+33': '法国',
      '+34': '西班牙',
      '+351': '葡萄牙',
      '+423': '列支敦士登',
      '+43': '奥地利',
      '+48': '波兰',
      '+39': '意大利',
    },
    },
  };
  

  const englishNames = {
    en: 'English',
    de: 'German',
    fr: 'French',
    it: 'Italian',
    es: 'Spanish',
    zh: 'Chinese',
  };
  
 
  const selectedLanguage = ref(localStorage.getItem('language') || '');
  
  function setLanguage(lang) {
  localStorage.setItem('language', lang);
  window.location.reload(); 
}

  
  function t(key) {
    const lang = selectedLanguage.value || 'en';
    return (
      key
        .split('.')
        .reduce((o, i) => (o ? o[i] : null), languages[lang]) || key
    );
  }
  
  function getEnglishName(lang) {
    return englishNames[lang] || lang;
  }
  
  
  export function useLanguage() {
    return {
      languages,
      selectedLanguage,
      setLanguage,
      t,
      getEnglishName, 
    };
  }



